### ISSUE TITLE
error in setup.py

### ISSUE THREAD

**Issue by raw937** [AlessioMilanese/classify-genomes#1]
python setup.py
 ------------------------------------------------------------------------------
|                           SETUP CLASSIFY-GENOMES                             |
 ------------------------------------------------------------------------------
Download the compressed motus database (~1Gb)
 954997496  [100.00%]

Check md5: MD5 verified
Extract files from the archive...Error: failed to extract files

**Comment by raw937** [comment]
ls -thor
total 708M
-rw-r----- 1 richard.white3    0 Jun 28  2017 mOTU.v2b.genes.len
-rw-r----- 1 richard.white3  23M Jun 28  2017 mOTU.v2b.padded.coords
-rw-r----- 1 richard.white3    0 Aug 20  2017 mOTU.v2b.nr.padded.ann
-rw-r----- 1 richard.white3  13K Aug 20  2017 mOTU.v2b.nr.padded.amb
-rw-r----- 1 richard.white3 618M Aug 20  2017 mOTU.v2b.nr.padded
-rw-r----- 1 richard.white3    0 Aug 20  2017 mOTU.v2b.nr.padded.bwt
-rw-r----- 1 richard.white3    0 Aug 20  2017 mOTU.v2b.nr.padded.pac
-rw-r----- 1 richard.white3    0 Aug 20  2017 mOTU.v2b.nr.padded.sa
-rw-r----- 1 richard.white3  13M Nov  1  2017 bam_header_nr
-rw-r----- 1 richard.white3 158M Feb 19  2018 mOTU.v2b.centroids.reformatted.padded
-rw-r----- 1 richard.white3    0 Feb 19  2018 mOTU.v2b.centroids.reformatted.padded.bwt
-rw-r----- 1 richard.white3    0 Feb 19  2018 mOTU.v2b.centroids.reformatted.padded.pac
-rw-r----- 1 richard.white3    0 Feb 19  2018 mOTU.v2b.centroids.reformatted.padded.ann
-rw-r----- 1 richard.white3 4.3K Feb 19  2018 mOTU.v2b.centroids.reformatted.padded.amb
-rw-r----- 1 richard.white3    0 Feb 19  2018 mOTU.v2b.centroids.reformatted.padded.sa
-rw-r----- 1 richard.white3    0 Feb 19  2018 bam_header_cen
-rw-r----- 1 richard.white3    0 Feb 19  2018 mOTU.v2b.padded.coords_for_centroids
-rw-r----- 1 richard.white3    0 Mar 15  2018 mOTU-LG.map.line.tsv
-rw-r----- 1 richard.white3 3.5M Mar 15  2018 mOTU-LG.map.tsv
-rw-r----- 1 richard.white3    0 Mar 15  2018 mOTU.v2b.map
-rw-r----- 1 richard.white3 953K Mar 15  2018 prok-refdb-v11.0.0_specI-v2_taxonomy_v1.map
-rw-r----- 1 richard.white3 416K Mar 15  2018 mOTULG.taxonomy
-rw-r----- 1 richard.white3  13M Apr 23  2018 mOTU.v2b.centroids.reformatted.padded.annotations
-rw-r----- 1 richard.white3 415K Jun 10  2018 short_names.txt
drwxr-x--- 2 richard.white3 4.0K Jun 10  2018 test
-rw-r----- 1 richard.white3 4.5M Aug 23  2018 CAMI_Sep_2015_mOTUs_2.0.0.tsv

**Comment by raw937** [comment]
tar -zxvf db_mOTU.tar.gz 
db_mOTU/
db_mOTU/mOTU-LG.map.tsv
db_mOTU/mOTULG.taxonomy
db_mOTU/CAMI_Sep_2015_mOTUs_2.0.0.tsv
db_mOTU/mOTU.v2b.centroids.reformatted.padded.annotations
db_mOTU/short_names.txt
db_mOTU/bam_header_nr
db_mOTU/mOTU.v2b.padded.coords
db_mOTU/mOTU.v2b.centroids.reformatted.padded
db_mOTU/mOTU.v2b.centroids.reformatted.padded.amb
db_mOTU/prok-refdb-v11.0.0_specI-v2_taxonomy_v1.map
db_mOTU/mOTU.v2b.nr.padded.amb
db_mOTU/mOTU.v2b.nr.padded
tar: db_mOTU/mOTU.v2b.nr.padded: Cannot close: Disk quota exceeded
db_mOTU/bam_header_cen
tar: db_mOTU/bam_header_cen: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.nr.padded.sa
tar: db_mOTU/mOTU.v2b.nr.padded.sa: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.centroids.reformatted.padded.pac
tar: db_mOTU/mOTU.v2b.centroids.reformatted.padded.pac: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.centroids.reformatted.padded.ann
tar: db_mOTU/mOTU.v2b.centroids.reformatted.padded.ann: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.nr.padded.ann
tar: db_mOTU/mOTU.v2b.nr.padded.ann: Cannot close: Disk quota exceeded
db_mOTU/test/
db_mOTU/test/test2_for.fastq
tar: db_mOTU/test/test2_for.fastq: Cannot close: Disk quota exceeded
db_mOTU/test/test2.motus
tar: db_mOTU/test/test2.motus: Cannot close: Disk quota exceeded
db_mOTU/test/test1_single.fastq
tar: db_mOTU/test/test1_single.fastq: Cannot close: Disk quota exceeded
db_mOTU/test/test2_rev.fastq
tar: db_mOTU/test/test2_rev.fastq: Cannot close: Disk quota exceeded
db_mOTU/test/test1.motus
tar: db_mOTU/test/test1.motus: Cannot close: Disk quota exceeded
db_mOTU/mOTU-LG.map.line.tsv
tar: db_mOTU/mOTU-LG.map.line.tsv: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.centroids.reformatted.padded.sa
tar: db_mOTU/mOTU.v2b.centroids.reformatted.padded.sa: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.nr.padded.pac
tar: db_mOTU/mOTU.v2b.nr.padded.pac: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.nr.padded.bwt
tar: db_mOTU/mOTU.v2b.nr.padded.bwt: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.genes.len
tar: db_mOTU/mOTU.v2b.genes.len: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.centroids.reformatted.padded.bwt
tar: db_mOTU/mOTU.v2b.centroids.reformatted.padded.bwt: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.padded.coords_for_centroids
tar: db_mOTU/mOTU.v2b.padded.coords_for_centroids: Cannot close: Disk quota exceeded
db_mOTU/mOTU.v2b.map
tar: db_mOTU/mOTU.v2b.map: Cannot close: Disk quota exceeded
tar: Exiting with failure status due to previous errors

**Comment by AlessioMilanese** [comment]
try to install in a different path, where you have some space left.

**Comment by raw937** [comment]
it appears that I have enough space on that drive. 
I am testing an install in another location.
Well, that worked. 
Thanks!

**Comment by AlessioMilanese** [comment]
I'm glad it worked!
I'm closing the issue.
All the best,
alessio
