### ISSUE TITLE
runs to states "extract genes" with no output

### ISSUE THREAD

**Issue by raw937** [AlessioMilanese/classify-genomes#2]
?

**Comment by AlessioMilanese** [comment]
There are many dependencies:
* Perl 5.24.0
* cdbtools
* Prodigal 2.6.3
* Python 2.7.12
* SAMtools 1.3.1
* HMMER 3.1b2
* vsearch

I would use conda for the dependencies:
```
cd classify-genomes/env
conda env create -f classify-genomes.yaml
source activate classify-genomes-ENV
```

Do you have conda installed already? 
If not, on linux you can install with:
```
curl -O https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
bash Anaconda3-5.0.1-Linux-x86_64.sh
```
or check:https://www.digitalocean.com/community/tutorials/how-to-install-the-anaconda-python-distribution-on-ubuntu-16-04
