### ISSUE TITLE
No matches

### ISSUE THREAD

**Issue by raw937** [AlessioMilanese/classify-genomes#4]
Wondering why no matches are occurring?

**Comment by AlessioMilanese** [comment]
Can you describe more?

**Comment by raw937** [comment]
It pulls the marker genes in the outputs. It makes a marker file. It makes the single line out out saying no matches.

**Comment by AlessioMilanese** [comment]
Can you copy here the command that you wrote and also the result that you obtain?
In this way I will understand better what's going on.

**Comment by AlessioMilanese** [comment]
If you mean:
```
Consensus NCBI ID: no match
Consensus taxonomy: no match
Consensus mOTUs: no match
```
it means that there the fasta file that you gave as input has no match to the mOTUs taxonomy.

**Comment by AlessioMilanese** [comment]
There can be two reasons for this:

1.  there are no marker genes detected (in which case you will see: `Number of detected genes: 0`)
2. the marker genes that you detect do not have a match to the mOTUs taxonomy. If you see something like:
```
Number of detected genes: 8
Number of mapped genes: 0
```
This means that this genome (or MAG) represent a new species that is not present in the mOTUs database.

**Comment by raw937** [comment]
command:
classify-genomes bin.6.fa -o bin.6_cg -m bin.6.markers -s -t 24
 head bin.6_cg 
bin.6.fa	no match	no match	no match	10	0	0	NA
head bin.6.markers 
>COG0541_1
ATGTTTGATAATTTAACCGATCGTTTGTCGCGCTCGCTGCGCAACATCAGCGGCCGTGGGCGCCTTACCG
AAGACAATGTGAAAGAAACGCTGCGCGAAGTGCGCATGGCGTTGCTCGAAGCCGACGTGGCGCTGCCCGT
head bin.6.fa.fai
F1_k121_21195	7762	15	60	61
F1_k121_53125	62325	7922	60	61

checkm and prokka picked up the taxonomy. It would be a super bummer if it couldn't be found as a mOTU.

**Comment by AlessioMilanese** [comment]
Note that we expect to see 10 marker genes per genome (this is a property of the 10 genes that we selected: they are present in single copy and they are universal to all species).
In your case, it means that there is no mOTU that represents that MAG/genome.
