### ISSUE TITLE
Use the tool with other versions of the mOTUs database?

### ISSUE THREAD

**Issue by jonathanth** [AlessioMilanese/classify-genomes#8]
Hi!

First of all, thanks for sharing this great tool.

I was curious if you have any plans to enable the tool to be used with different versions of the mOTUs database. As far as i can tell, the database for classify-genomes is formatted quite differently from the one that ships with the main mOTUs install?
In my use case, that would be version 2.11.

bw 
Jonathan

**Comment by AlessioMilanese** [comment]
Hi Jonathan,

>First of all, thanks for sharing this great tool.

Thanks for your interest! 

>I was curious if you have any plans to enable the tool to be used with different versions of the mOTUs database. As far as i can tell, the database for classify-genomes is formatted quite differently from the one that ships with the main mOTUs install?
In my use case, that would be version 2.11.

Currently it's using mOTUs database version 2.5.0: https://github.com/AlessioMilanese/classify-genomes/blob/master/setup.py#L10

In order to use the database 2.1.1, it should be enough to replace few lines in the [setup file](https://github.com/AlessioMilanese/classify-genomes/blob/master/setup.py). In particular change lines 10, 11 and 12 to:
```
motus_version = "2.1.1"
link_db = "https://zenodo.org/record/2583171/files/db_mOTU_v2.1.1.tar.gz"
md5_db = "5a0cbf7c0db437d1c424846a94d03e8e"
```

I didn't try. Let me know if it works! (Note that you have to re-run the setup.py)

**Comment by jonathanth** [comment]
Awesome, thanks! Will give it a try and let you know.

**Comment by jonathanth** [comment]
Hi Alessio,

The script fails at the end when trying to clean up unused files, ie the line
os.remove(os.path.abspath(os.path.join(relative_path, 'db_mOTU/db_mOTU_bam_header_CEN')))

The reason is that the two versions of the database are formatted differently, see below.
Would it be sufficient to just rename some of the files to match the v2.5.0 or is the structure different as well? 

bw jonathan
```
~/apps/classify-genomes/dbversions$ tar -xvf db_mOTU_v2.1.1.tar.gz 
db_mOTU/
db_mOTU/test/
db_mOTU/test/test2.motus
db_mOTU/test/test2_for.fastq
db_mOTU/test/test2_rev.fastq
db_mOTU/test/test1.motus
db_mOTU/test/test1_single.fastq
db_mOTU/mOTU.v2b.centroids.reformatted.padded.bwt
db_mOTU/mOTU-LG.map.tsv
db_mOTU/mOTU.v2b.centroids.reformatted.padded.ann
db_mOTU/mOTU-LG.map.line.tsv
db_mOTU/mOTU.v2b.genes.len
db_mOTU/mOTU.v2b.nr.padded.ann
db_mOTU/mOTU.v2b.nr.padded.bwt
db_mOTU/short_names.txt
db_mOTU/mOTU.v2b.centroids.reformatted.padded
db_mOTU/mOTU.v2b.map
db_mOTU/mOTU.v2b.nr.padded.amb
db_mOTU/mOTU.v2b.padded.coords
db_mOTU/mOTULG.taxonomy
db_mOTU/prok-refdb-v11.0.0_specI-v2_taxonomy_v1.map
db_mOTU/mOTU.v2b.padded.coords_for_centroids
db_mOTU/mOTU.v2b.centroids.reformatted.padded.annotations
db_mOTU/bam_header_cen
db_mOTU/mOTU.v2b.nr.padded.sa
db_mOTU/mOTU.v2b.nr.padded.pac
db_mOTU/mOTU.v2b.centroids.reformatted.padded.pac
db_mOTU/mOTU.v2b.centroids.reformatted.padded.sa
db_mOTU/mOTU.v2b.nr.padded
db_mOTU/CAMI_Sep_2015_mOTUs_2.0.0.tsv
db_mOTU/bam_header_nr
db_mOTU/mOTU.v2b.centroids.reformatted.padded.amb

~/apps/classify-genomes/dbversions$ mv db_mOTU db_mOTU_v2.1.1

~/apps/classify-genomes/dbversions$ tar -xvf db_mOTU_v2.5.0.tar.gz 
db_mOTU/
db_mOTU/db_mOTU_test/
db_mOTU/db_mOTU_test/test1.motus
db_mOTU/db_mOTU_test/test1_single.fastq
db_mOTU/db_mOTU_DB_CEN.fasta
db_mOTU/db_mOTU_DB_CEN.fasta.annotations
db_mOTU/db_mOTU_DB_CEN.fasta.pac
db_mOTU/db_mOTU_DB_CEN.fasta.ann
db_mOTU/db_mOTU_DB_CEN.fasta.amb
db_mOTU/db_mOTU_DB_CEN.fasta.bwt
db_mOTU/db_mOTU_padding_coordinates_CEN.tsv
db_mOTU/db_mOTU_genes_length_NR
db_mOTU/db_mOTU_DB_NR.fasta
db_mOTU/db_mOTU_DB_CEN.fasta.sa
db_mOTU/db_mOTU_DB_NR.fasta.pac
db_mOTU/db_mOTU_DB_NR.fasta.ann
db_mOTU/db_mOTU_DB_NR.fasta.amb
db_mOTU/db_mOTU_padding_coordinates_NR.tsv
db_mOTU/db_mOTU_DB_NR.fasta.bwt
db_mOTU/db_mOTU_bam_header_CEN
db_mOTU/README
db_mOTU/db_mOTU_MAP_MGCs_to_mOTUs.tsv
db_mOTU/db_mOTU_bam_header_NR
db_mOTU/db_mOTU_taxonomy_meta-mOTUs.tsv
db_mOTU/db_mOTU_MAP_MGCs_to_mOTUs_in-line.tsv
db_mOTU/db_mOTU_MAP_genes_to_MGCs.tsv
db_mOTU/db_mOTU_taxonomy_ref-mOTUs.tsv
db_mOTU/db_mOTU_taxonomy_ref-mOTUs_short_names.tsv
db_mOTU/db_mOTU_taxonomy_CAMI.tsv
db_mOTU/db_mOTU_DB_NR.fasta.sa

```

**Comment by AlessioMilanese** [comment]
I created a new setup file:
[setup_2.1.py.zip](https://github.com/AlessioMilanese/classify-genomes/files/7312919/setup_2.1.py.zip)

after unzip it, you can run:
```
python setup_2.1.py
```

After that you go to the repo with the database and change some names:
```
cd db_mOTU/

mv mOTU.v2b.centroids.reformatted.padded db_mOTU_DB_CEN.fasta
mv mOTU.v2b.map db_mOTU_MAP_genes_to_MGCs.tsv
mv mOTULG.taxonomy db_mOTU_taxonomy_meta-mOTUs.tsv
mv mOTU.v2b.nr.padded db_mOTU_DB_NR.fasta
mv mOTU-LG.map.tsv db_mOTU_MAP_MGCs_to_mOTUs.tsv
mv prok-refdb-v11.0.0_specI-v2_taxonomy_v1.map  db_mOTU_taxonomy_ref-mOTUs.tsv
```

**Comment by jonathanth** [comment]
That works, thank you so much!

**Comment by AlessioMilanese** [comment]
Nice! Glad it worked.
